spring:
  rabbitmq:
    host: 192.168.18.100
    port: 5672
    username: guest
    password: 123456
    virtual-host: /

#    cannot switch from tx to confirm mode, class-id=85, method-id=10)
#spring:
#  rabbitmq:
#    host: 192.168.18.100
#    port: 5672
#    username: guest
#    password: 123456
#    virtual-host: /
#    publisher-confirm-type: CORRELATED # 交换机的确认
#    publisher-returns: true # 队列的确认
#logging:
#  level:
#    com.atguigu.mq.config.MQProducerAckConfig: info



